import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TitleBar from "@/components/atoms/title-bar";
import UserProvider from "@/components/_auth/user-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen w-full overflow-x-clip bg-white text-black`}
      >
        <UserProvider>
          <nav className="absolute left-0 top-0 h-20 w-full overflow-clip">
            <TitleBar title={"Ankiety"} />
          </nav>
          <main className="h-full overflow-auto bg-sky-100 pt-20">
            {children}
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
